# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Values.config.visualizer.name }}"
  name: deployment-visualizer
  namespace: "{{ .Values.namespace }}" 

spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.config.visualizer.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.config.visualizer.name }}"
    spec:
      containers:
      - name: ia-visualizer
        image: "{{ .Values.DOCKER_REGISTRY }}ia_visualizer:{{ .Values.EII_VERSION }}"
        volumeMounts:
        {{- if eq .Values.config.visualizer.IPC true}}
        - name: {{ .Values.volumes.eii_socket.name }}
          mountPath: {{ .Values.volumes.eii_socket.location }}
        {{- end }}
        - name: {{ .Values.volumes.savedimage.name }}
          mountPath: {{ .Values.volumes.savedimage.location }}
        - name: tmp
          mountPath: /tmp/.X11-unix
        {{ if eq .Values.env.DEV_MODE false}}
        - name: etcd-certs
          mountPath: /run/secrets/etcd/
        {{ end }}
        env:
        - name: AppName
          value: "Visualizer"
        - name: DISPLAY
          value: ':0'
        - name: IMAGE_DIR
          value: "{{.Values.env.EII_INSTALL_PATH }}/saved_images"
        - name: DEV_MODE
          value: '{{ .Values.env.DEV_MODE }}'
        - name: PROFILING_MODE
          value: '{{ .Values.env.PROFILING_MODE }}' 
        - name: ETCD_HOST
          value: etcd
        - name: ETCD_CLIENT_PORT
          value: '{{.Values.config.etcd.client_port }}'
        {{ if eq .Values.env.DEV_MODE false}}
        - name: CONFIGMGR_CACERT
          value: "/run/secrets/etcd/ca_certificate.pem"
        - name: CONFIGMGR_CERT
          value: "/run/secrets/etcd/Visualizer_client_certificate.pem"
        - name: CONFIGMGR_KEY
          value: "/run/secrets/etcd/Visualizer_client_key.pem"
        {{ end }} 
          # MessageBus Endpoint Configuration
        - name: CertType
          value: "zmq"
        {{- $global := . -}}
        {{- range $instance_idx := until (int .Values.num_video_instances) -}}
        {{- $instance := "" }}
        {{- $subscriber_port := "" }}
        {{- if eq (int $global.Values.num_video_instances) 1 }}
        {{- $subscriber_port = $global.Values.config.video_analytics.publish_port }}
        {{- $instance = "" }}
        {{- end }}
        {{- if gt (int $global.Values.num_video_instances) 1 }}
        {{- $subscriber_port = add $global.Values.config.video_analytics.publish_port  $instance_idx }}
        {{- $instance = add 1 $instance_idx }}
        {{- end }}
        {{- if eq $global.Values.config.visualizer.IPC false}}
        - name: SUBSCRIBER_default{{ $instance }}_ENDPOINT
          value: "{{ $global.Values.config.video_analytics.name }}{{ $instance }}:{{ $subscriber_port }}"
        - name: SUBSCRIBER_default{{ $instance }}_TYPE
          value: "zmq_tcp"
        {{- else }}
        - name: SUBSCRIBER_default{{ $instance }}_ENDPOINT
          value: "{{ $global.Values.env.SOCKET_DIR }}"
        - name: SUBSCRIBER_default{{ $instance }}_TYPE
          value: "zmq_ipc"
        {{- end }}
        {{- end }}

      volumes:
      {{- if eq .Values.config.visualizer.IPC true}}
      - name: {{ .Values.volumes.eii_socket.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.eii_socket.name }}
      {{- end }}
      - name: {{ .Values.volumes.savedimage.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.savedimage.name }}
      - name: tmp
        hostPath:
          path: "/tmp/.X11-unix"

      {{ if eq .Values.env.DEV_MODE false}}
      - name: etcd-certs
        secret:
          secretName: eii-certs
          items:
          - key: ca_certificate.pem
            path: ca_certificate.pem          
          - key: Visualizer_client_certificate.pem
            path: Visualizer_client_certificate.pem          
          - key: Visualizer_client_key.pem
            path: Visualizer_client_key.pem          
      {{ end }}    
